[build]
  publish = "dist"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "20"

# Removed function-specific environment variables to avoid 4KB limit
# All environment variables are now handled at the site level in Netlify dashboard


