[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  timeout = 30

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

