[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/api/auth/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "authorization, x-client-info, apikey, content-type"

[[redirects]]
  from = "/api/auth/*"
  to = "https://kstmyodjnckgoosidsbb.supabase.co/auth/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200