[build]
  publish = "dist"
  command = "npm install && npm run build"

[functions]
  directory = "netlify/functions"

# OAuth callback MUST go to the function, not React
[[redirects]]
  from = "/.netlify/functions/simple-ebay-callback"
  to = "/.netlify/functions/simple-ebay-callback"
  status = 200
  force = true

# SPA fallback for everything else
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "20"

# Removed function-specific environment variables to avoid 4KB limit
# All environment variables are now handled at the site level in Netlify dashboard


